# Generated by Django 3.1.7 on 2021-05-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EComerce', '0002_carro_productos_proveedores_venta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
        migrations.RenameModel(
            old_name='Proveedores',
            new_name='Proveedor',
        ),
    ]
